#!/bin/bash

#PBS -N pyrad_ub_ind50_cov20
#PBS -q qcABI
#PBS -j oe
#PBS -o pyrad_ub_ind50_cov20.out
#PBS -m abe
#PBS -M tkchafin@email.uark.edu
#PBS -l nodes=1:ppn=48
#PBS -l walltime=20:00:00:00
#PBS -V 

export PATH=$PATH:/home/mussmann/local/bin/:/home/mrd1/acamel/local/bin


module purge
module load gcc/4.9.1 mkl python/2.7.11 muscle 

DIR=/storaged/tkchafin/gila/gila_pyrad_ch2/ind50_cov20
PAR=$DIR/params.txt

cd /scratch/$PBS_JOBID
cp $PAR .

pyrad -p params.txt -s 234567
mv * $DIR/.

